config/routes.rb
Rails.application.routes.draw do
  
  root to: "tasks#index"
  resources :tasks
  
  resources :users, only:[:new, :create]
  
  get "login" ,to: "sessions#new"
  post 'login', to: 'sessions#create'
  post 'logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length:{maximum:255}
  validates :status, presence: true, length:{maximum:10}
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  def require_user_logged_in
    unless logged_in?
      redirect_to login_path ,notice: "ログインしてください"
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_path
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :ensure_correct_user, only:[:show, :edit, :update, :destroy]
  
  def index
    @tasks =current_user.tasks.order(id: :desc).page(params[:page])
  end
  
  def show

  end
  
  def new
    @task = current_user.tasks.build 
  end
  
  def create
    @task = current_user.tasks.build (task_params)
    if @task.save
      flash[:success] = 'タスクが正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクが投稿されませんでした'
      render :new
    end
  end
  
  def edit
    
  end
  
  def update
    
    if current_user.tasks.update(task_params)
      flash[:success] = 'タスクが正常に更新されました'
      redirect_to @task      
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
     @task.destroy
     flash[:success] = 'タスクは正常に削除されました'
     
     redirect_to("/")
  end
  
  private
  
  def task_params
    params.require(:task).permit(:content,:status)
  end
  
  def ensure_correct_user
    @task = Task.find_by(id: params[:id])
    if @task.user_id != current_user.id
      flash[:success] = '権限がありません'
      redirect_to tasks_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  
  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_task.html.erb
<div class="row">
  <div class="col-6">
    <% flash.each do |task_type, task| %>
      <div class="alert alert-<%= task_type %>"><%= task %></div>
    <% end %> 
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>


  <header>
    <nav class="navbar navbar-expand-sm navbar-light bg-info">
      <%= link_to "TASKリスト", "/" ,class: "navbar-brand" %>
    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="nav-bar">
      <ul class="navbar-nav">
        <% if current_user || nil %>
          <li class="nav-item"><%= link_to "ようこそ"+current_user.name+"さん", "/" , class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "タスク作成", "/tasks/new" , class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "ログアウト", logout_path , method: :post, class: "nav-link"%></li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", new_user_path , class: "nav-link"%></li>
        <% end %>
        
        
      </ul>
    </div>
    
    </nav>
    
  </header>
    <div class="ml-3 mt-3">
      <%= render 'layouts/flash_task' %>
      <%= yield %>
    </div>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: task, local: true) do |f| %>
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %> 
          </ul>
        </div>
      <% end %>
      
      <div class="form-group row">
        <label class="col-sm-3 col-form-label text-center"><%='タスク' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :content ,class: "form-control"%>
        </div>
      </div>  
      
      <div class="form-group row">
        <label class="col-sm-3 col-form-label text-center"><%='ステータス' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :status ,class: "form-control"%>
        </div>
      </div>
      
      <%= f.submit '投稿',class: 'btn btn-primary' %>
      
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %>タスク編集ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-6">
  <table class="table table-bordered">
    <tr>
      <th class="text-center">id</th>
      <th class="text-center">タスク</th>
      <th class="text-center">ステータス</th>
    </tr>
    <% @tasks.each do |task| %>
      <tr>
        <td class="text-center"><%= link_to task.id,task %></td>
        <td class="text-center"><%= task.content %></td>
        <td class="text-center"><%= task.status%></td>
      </tr>
    <% end%>
  </table>
  </div>
</div>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>
<div class="row">
  <div class="col-6">
    <table class="table table-bordered">
      <tr>
        <th>id</th>
        <td><%= @task.id %></td>
      </tr>
      <tr>
        <th>タスク</th>
        <td><%= @task.content %></td>
      </tr>
      <tr>
        <th>ステータス</th>
        <td><%= @task.status %></td>
      </tr>
</table>
</div>
</div>

<%= link_to "編集",edit_task_path(@task),class: "btn btn-primary" %>
<%= link_to "削除",@task,method: :delete ,class: "btn btn-danger",data: { confirm: '本当に削除してよろしいですか？' } %>
<%= link_to "一覧へ戻る",tasks_path ,class: "btn btn-info" %>

app/views/users/new.html.erb
<h1>新規作成</h1>

<div class="row">
  <div class="col-6">
    <%= form_with(model:@user, local: true) do |f| %>
    
      <% if @user.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %> 
          </ul>
        </div>
      <% end %>
      
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='name' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :name ,class: "form-control"%>
        </div>
      </div>    
      
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='E-mail' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :email ,class: "form-control"%>
        </div>
      </div>  
  
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='PassWord' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :password ,class: "form-control" ,type:"password"%>
        </div>
    </div>
    
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='Confirmation' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :password_confirmation ,class: "form-control" ,type:"password"%>
        </div>
    </div>
    
      <%= f.submit '作成',class: 'btn btn-primary' %>
      
    <% end %>
    <%= link_to("戻る","/login", class:'btn btn-success mt-2') %>
  </div>
</div>

app/views/users/top.html.erb
<h1>ログイン</h1>

<div class="row">
  <div class="col-6">
    <%= form_with(model:@user, local: true) do |f| %>
  
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='E-mail' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :email ,class: "form-control"%>
        </div>
      </div>  
  
    <div class="form-group row">
      <label class="col-sm-3 col-form-label text-center"><%='PassWord' %></label>
        <div class=" col-sm-9">
          <%= f.text_field :password ,class: "form-control"%>
        </div>
    </div>
      <%= f.submit 'ログイン',class: 'btn btn-primary' %>
    <% end %>
    <%= link_to("新規作成","/users/new", class: "btn btn-warning mt-2") %>
  </div>
</div>